name: ToolBelt
main: com.github.peter200lx.toolbelt.ToolBelt
version: maven-version-number
website: https://github.com/Peter200lx/ToolBelt
author: peter200lx
description: >
             Go armed out into the world with an assortment of gizmos at your side.
commands:
  toolbelt:
    description: Holder command for reload and more
    aliases: tb
    usage: |
           /<command> [reload|tools|on|off]
           Example: /<command> - Prints help for plugin.
           Example: /<command> reload - Reloads settings from disk
           Example: /<command> tools - Lists tools available to player
           Example: /<command> on|off - Enables or disables ToolBelt tools for the player
permissions:
    toolbelt.*:
        default: false
        description: Do not use this (.print. and .ranks. do not like *)
    toolbelt.reload:
        default: op
        description: Allows the player to reload toolbelt from configuration file.
    toolbelt.print.*:
        default: false
        description: Do not use this. Give any user only one of the sub-permissions.
    toolbelt.print.debug:
        default: false
        description: Print all messages including ones that give debugging information.
    toolbelt.print.hint:
        default: false
        description: Print all quieter messages + hints for using tools.
    toolbelt.print.info:
        default: false
        description: Print all quieter messages + informational notices for tools.
    toolbelt.print.warning:
        default: false
        description: Print all quieter messages + warnings on wrong tool use.
    toolbelt.print.important:
        default: false
        description: Print important messages, such as loaded paint material and such.
    toolbelt.print.cmd:
        default: false
        description: Print only responses to user typed commands.
    toolbelt.tool.*:
        description: Gives access to the tool specific permissions for toolbelt
        default: op
        children:
            toolbelt.tool.dupe: true
            toolbelt.tool.scroll: true
            toolbelt.tool.paint: true
            toolbelt.tool.paint: true
            toolbelt.tool.paint.range: true
            toolbelt.tool.leap: true
            toolbelt.tool.leap.tel: true
            toolbelt.tool.leap.fly: true
            toolbelt.tool.leap.free: true
            toolbelt.tool.phax: true
            toolbelt.tool.phax.range: true
            toolbelt.tool.ruler: true
            toolbelt.tool.watch: true
            toolbelt.tool.watch.server: true
            toolbelt.tool.sledge: true
            toolbelt.tool.pliers: true
            toolbelt.tool.shovel: true
            toolbelt.tool.saw: true
            toolbelt.tool.tree: true
    toolbelt.tool.dupe:
        description: Allows the player to use the duplicator tool.
    toolbelt.tool.scroll:
        description: Allows the player to use the data scrolling tool.
    toolbelt.tool.paint:
        description: Allows the player to use the paint tool.
    toolbelt.tool.paint.range:
        description: Allows the player to use the paint tool at a distance.
    toolbelt.tool.leap:
        description: Allows the player to make huge leaps with the right tool.
    toolbelt.tool.leap.tel:
        description: Allows the player to teleport by crouching while leaping.
    toolbelt.tool.leap.fly:
        description: Allows the player to enter creative flying mode.
    toolbelt.tool.leap.free:
        description: Allows the player to leap without cost (Only needed if tools.leap.cost > 0)
    toolbelt.tool.phax:
        description: Allows the player to remove blocks in one click, with or without physics applied.
    toolbelt.tool.phax.range:
        description: Allows the player to use the PickHax tool at a distance.
    toolbelt.tool.ruler:
        description: Allows the player to measure distances easily with the ruler.
    toolbelt.tool.watch:
        description: Allows the player to set the time to day or night for themselves with the watch tool.
    toolbelt.tool.watch.server:
        description: Allows the player to set the server time.
    toolbelt.tool.sledge:
        description: Allows the player to push or pull blocks.
    toolbelt.tool.pliers:
        description: Allows the player to copy and push or pull blocks.
    toolbelt.tool.shovel:
        description: Allows the player to clear large amounts of (by default) stone, dirt, grass, sand and gravel.
    toolbelt.tool.saw:
        description: Allows the player to clear large amounts of (by default) logs, leaves and vines.
    toolbelt.tool.tree:
        description: Allows the player to plant various trees.
    toolbelt.rank.*:
        default: false
        description: (Do not use .rank.*) Optional functionality, read help/Ranks.txt for more information

